spring.application.name=punsAndParadise

#DB configuration:
spring.datasource.url=jdbc:postgresql://localhost:5432/punsAndParadise
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
